# Generated by Django 5.1.2 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('event_category', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
